version: "3.8"

services:
  client:
    build:
      context: ..
      dockerfile: docker/client.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://server:8000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      - server

  server:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CLIENT_APP_URL=http://client:3000
      - APP_URL=http://localhost:8000
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_USERNAME=${KAFKA_USERNAME}
      - KAFKA_PASSWORD=${KAFKA_PASSWORD}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_SSL_ENABLED=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis
#   redis:
#     image: redis:alpine
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data

# volumes:
#   redis_data:
